// Copyright (C) 2026, Maifee Ul Asad<maifeeulasad@gmail.com>, BSD-3-Clause
// SPDX-License-Identifier: BSD-3-Clause

// Generates a runnable ROHD testbench scaffold for a converted module: it
// wires up a clock and reset (when present), instantiates the DUT, dumps a
// VCD waveform, and leaves TODO markers for stimulus and output checks.
// SystemVerilog has no "generate a testbench" input, so this produces a
// starting point rather than a complete test. Parts of this implementation
// were generated with LLM assistance.

import '../analysis/symbol.dart';
import '../ir/ir.dart';
import 'naming_strategy.dart';

/// Emits a ROHD testbench scaffold from a [ModuleDeclaration].
class TestbenchScaffold {
  final NamingStrategy namingStrategy;

  const TestbenchScaffold({this.namingStrategy = const NamingStrategy()});

  /// Generates the scaffold source. [dutImport] is the import path of the
  /// generated module file (e.g. `adder.dart`).
  String generate(ModuleDeclaration module, {required String dutImport}) {
    final className = namingStrategy.toClassName(module.name);
    final params = _paramDefaults(module);
    final inputs =
        module.ports.where((p) => p.direction != PortDirection.output).toList();
    final outputs =
        module.ports.where((p) => p.direction == PortDirection.output).toList();
    final clock = inputs
        .where((p) => _isClock(p.name))
        .cast<PortDeclaration?>()
        .firstWhere((_) => true, orElse: () => null);
    final reset = inputs
        .where((p) => _isReset(p.name))
        .cast<PortDeclaration?>()
        .firstWhere((_) => true, orElse: () => null);
    final data =
        inputs.where((p) => !_isClock(p.name) && !_isReset(p.name)).toList();

    final b = StringBuffer();
    if (clock != null) b.writeln("import 'dart:async';");
    b.writeln("import 'package:rohd/rohd.dart';");
    b.writeln("import '$dutImport';");
    b.writeln();
    b.writeln('/// Testbench scaffold for `$className`, generated by sv2rohd.');
    b.writeln('///');
    b.writeln('/// Fill in the stimulus and checks at the TODO markers, then '
        'run:');
    b.writeln('///   dart run <this file>');
    b.writeln('Future<void> main() async {');

    // Signal declarations.
    if (clock != null) {
      final name = namingStrategy.toCamelCase(clock.name);
      b.writeln('  // 10-time-unit clock.');
      b.writeln('  final $name = SimpleClockGenerator(10).clk;');
    }
    for (final port in inputs) {
      if (clock != null && port.name == clock.name) continue;
      final name = namingStrategy.toCamelCase(port.name);
      final w = _portWidth(port.width, params);
      final widthArg = w == 1 ? '' : ', width: $w';
      b.writeln("  final $name = Logic(name: '${port.name}'$widthArg);");
    }
    b.writeln();

    // DUT.
    final args =
        inputs.map((p) => namingStrategy.toCamelCase(p.name)).join(', ');
    if (module.parameters.where((p) => !p.isLocal).isNotEmpty) {
      b.writeln('  // Parameters use their defaults; override as named args '
          'if needed.');
    }
    b.writeln('  final dut = $className($args);');
    b.writeln('  await dut.build();');
    b.writeln();
    b.writeln('  // Dump a VCD waveform for inspection.');
    b.writeln("  WaveDumper(dut, outputPath: '${module.name}.vcd');");
    b.writeln();

    if (clock != null) {
      final clk = namingStrategy.toCamelCase(clock.name);
      b.writeln('  // Initial input values (reset asserted).');
      if (reset != null) {
        final r = namingStrategy.toCamelCase(reset.name);
        final active = _resetActiveLow(reset.name) ? '0' : '1';
        b.writeln('  $r.inject($active);');
      }
      for (final port in data) {
        b.writeln('  ${namingStrategy.toCamelCase(port.name)}.inject(0);');
      }
      b.writeln();
      b.writeln('  Simulator.setMaxSimTime(1000);');
      b.writeln('  unawaited(Simulator.run());');
      b.writeln();
      if (reset != null) {
        final r = namingStrategy.toCamelCase(reset.name);
        final inactive = _resetActiveLow(reset.name) ? '1' : '0';
        b.writeln('  // Hold reset for two cycles, then release it.');
        b.writeln('  await $clk.nextPosedge;');
        b.writeln('  await $clk.nextPosedge;');
        b.writeln('  $r.inject($inactive);');
        b.writeln();
      }
      b.writeln('  // TODO: drive stimulus, one cycle at a time.');
      for (final port in data) {
        b.writeln('  ${namingStrategy.toCamelCase(port.name)}.inject(0);');
      }
      b.writeln('  await $clk.nextPosedge;');
      b.writeln();
      b.writeln('  // TODO: check outputs.');
      for (final port in outputs) {
        final name = namingStrategy.toCamelCase(port.name);
        b.writeln("  print('${port.name} = \${dut.$name.value.toInt()}');");
      }
      b.writeln();
      b.writeln('  await Simulator.endSimulation();');
    } else {
      // Purely combinational: inject inputs, then run the simulator briefly
      // so the outputs settle before they are read.
      b.writeln('  // TODO: drive stimulus.');
      for (final port in data) {
        b.writeln('  ${namingStrategy.toCamelCase(port.name)}.inject(0);');
      }
      b.writeln();
      b.writeln('  Simulator.setMaxSimTime(10);');
      b.writeln('  await Simulator.run();');
      b.writeln();
      b.writeln('  // TODO: check outputs.');
      for (final port in outputs) {
        final name = namingStrategy.toCamelCase(port.name);
        b.writeln("  print('${port.name} = \${dut.$name.value.toInt()}');");
      }
    }

    b.writeln('}');
    return b.toString();
  }

  // ── Width / parameter evaluation ─────────────────────────────────

  Map<String, int> _paramDefaults(ModuleDeclaration module) {
    final env = <String, int>{};
    for (final param in module.parameters) {
      if (param.defaultValue == null) continue;
      final value = _evalInt(param.defaultValue!, env);
      if (value != null) env[param.name] = value;
    }
    return env;
  }

  int _portWidth(VectorWidth? width, Map<String, int> env) {
    if (width == null) return 1;
    final msb = width.msb != null ? _evalInt(width.msb!, env) : null;
    final lsb = width.lsb != null ? _evalInt(width.lsb!, env) : null;
    if (msb == null || lsb == null) return 1;
    return (msb - lsb).abs() + 1;
  }

  int? _evalInt(IrExpression e, Map<String, int> env) {
    if (e is LiteralExpression) return e.value is int ? e.value as int : null;
    if (e is IdentifierExpression) return env[e.identifier];
    if (e is UnaryExpression) {
      final v = _evalInt(e.operand, env);
      if (v == null) return null;
      return switch (e.operator) {
        UnaryOperator.minus => -v,
        UnaryOperator.plus => v,
        UnaryOperator.bitwiseNot => ~v,
        _ => null,
      };
    }
    if (e is BinaryExpression) {
      final l = _evalInt(e.left, env);
      final r = _evalInt(e.right, env);
      if (l == null || r == null) return null;
      return switch (e.operator) {
        BinaryOperator.add => l + r,
        BinaryOperator.subtract => l - r,
        BinaryOperator.multiply => l * r,
        BinaryOperator.divide => r != 0 ? l ~/ r : null,
        BinaryOperator.modulo => r != 0 ? l % r : null,
        BinaryOperator.shiftLeft => l << r,
        BinaryOperator.shiftRight => l >> r,
        _ => null,
      };
    }
    return null;
  }

  static bool _isClock(String name) {
    final n = name.toLowerCase();
    return n == 'clk' || n == 'clock' || n == 'clk_i';
  }

  static bool _isReset(String name) {
    final n = name.toLowerCase();
    return n == 'rst' ||
        n == 'rstn' ||
        n == 'rst_n' ||
        n == 'reset' ||
        n == 'resetn' ||
        n == 'reset_n' ||
        n == 'arst' ||
        n == 'arst_n';
  }

  static bool _resetActiveLow(String name) {
    final n = name.toLowerCase();
    return n.endsWith('_n') || n.endsWith('n');
  }
}
